Use a supported AJAX event for selectBooleanCheckbox
kitodo/kitodo-production pull request #4058
Opened 2020-10-21 12:15 UTC by matthias-ronge

Fixes #4051

2020-10-23 07:07 UTC, solth commented
> Fixes the bug described in #4051

With this syntax the issue won't be automatically closed when this PR gets merged ;) (there shouldn't be any text between "Fixes" and the issue number, I think)

<img width="317" alt="Bildschirmfoto 2020-10-23 um 09 06 38" src="https://user-images.githubusercontent.com/19183925/96967002-1b33bb80-150f-11eb-93ef-d6ddea9306cd.png">

2020-10-23 08:50 UTC, matthias-ronge commented
That was intentional in this case, because I am also interested in how best to describe in the XSD that a `<codomain type="boolean"/>` needs exactly one `<option value="..."/>`. At least with a comment, but I'm currently still looking for a formal description of this so that an editor will criticize it if it is wrong. So in this case I prefer to close the ticket manually.

2020-10-23 14:50 UTC, solth requested changes
It still does not work for me. 

When checking the checkbox and clicking "save", the corresponding `kitodo:metadata` element is written to the `meta.xml` file, but without a value. As I understand it, that works as you intended it to work (e.g. saving the metadata without explicit value equates to `true` and removing it equates to `false`).

The problem seems to be that _loading_ the `meta.xml` does not reflect this concept/design, as the saved `kitodo:metadata` element without an explicit value is not evaluated to `true` (a "checked" checkbox), but rather to `false` (e.g. an "unchecked" checkbox.)

2020-10-26 11:13 UTC, solth approved these changes
That did the trick!

Just one little suggestions to slightly simplify the "filter stream" expression.

2020-10-26 11:13 UTC, solth commented on Kitodo-API/src/main/java/org/kitodo/api/dataeditor/rulesetmanagement/SimpleMetadataViewInterface.java
> +            return getSelectItems().entrySet().stream().map(Entry::getKey).filter(StringUtils::isNotEmpty).findAny();
```suggestion
            return getSelectItems().keySet().stream().filter(StringUtils::isNotEmpty).findAny();
```

2020-10-26 11:13 UTC, solth commented on Kitodo-API/src/main/java/org/kitodo/api/dataeditor/rulesetmanagement/SimpleMetadataViewInterface.java
> +import java.util.Map.Entry;
```suggestion
```

2020-10-29 12:12 UTC, merged