remove use of processConverter
kitodo/kitodo-production pull request #4194
Opened 2021-02-17 12:50 UTC by Kathrin-Huber

fixes #4192

2021-02-17 13:24 UTC, solth commented on Kitodo/src/main/webapp/WEB-INF/templates/includes/processes/batchList.xhtml
> -                                         converter="#{batchConverter}"
The `BatchConverter` is not used anywhere else. It could probably be removed.

2021-02-18 08:47 UTC, solth requested changes
There is still something wrong with the batches. Trying to select one results in an error:
```
java.lang.ClassCastException: java.lang.String cannot be cast to org.kitodo.data.database.beans.Batch
	at org.kitodo.production.forms.BatchForm.changeSelectedBatch(BatchForm.java:470)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.el.parser.AstValue.invoke(AstValue.java:278)
	at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:274)
	at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
	at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
	at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
	at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
	at org.apache.myfaces.view.facelets.el.ContextAwareTagMethodExpression.invoke(ContextAwareTagMethodExpression.java:96)
	at javax.faces.event.MethodExpressionValueChangeListener.processValueChange(MethodExpressionValueChangeListener.java:77)
	at javax.faces.event.ValueChangeEvent.processListener(ValueChangeEvent.java:77)
	at javax.faces.component.UIComponentBase.broadcast(UIComponentBase.java:429)
...
```

2021-02-18 13:23 UTC, Kathrin-Huber commented
Turns out, the batch Converter is actually needed...

2021-02-18 18:12 UTC, solth commented
This is still fundamentally broken: removing the `ProcessConverter` class from `searchEdit.xhtml` prevents the `javax.faces.convert.ConverterException` mentioned in #4192, but now the `searchEdit` tab throws the following error when trying to create a process title from imported data:

<img width="716" alt="Bildschirmfoto 2021-02-18 um 17 35 40" src="https://user-images.githubusercontent.com/19183925/108401962-398b9880-721d-11eb-9bc8-b10005c99cd7.png">

This is because `CreateProcessForm.searchTab.originalProcess` is of class `Process` while `CreateProcessForm.searchTab.processesForChoiceList` contains  a list of `ProcessDTO`.  That was exactly the reason for the `ProcessConverter` in the first place.

Please try to import and save a process to verify your fix works.

2021-02-18 20:51 UTC, Kathrin-Huber commented
This was the problem: https://github.com/kitodo/kitodo-production/pull/4166/files#diff-be45863956c49903770aa7d9bf8ac0c46834c6cb563173112abbe93fcb0b74dcR63

2021-02-19 07:56 UTC, solth commented on Kitodo/src/main/java/org/kitodo/production/forms/createprocess/SearchTab.java
> +        return processes;
```suggestion
        return processes.stream().filter(BaseTemplateBean::getInChoiceListShown).collect(Collectors.toList());
```

2021-02-22 11:30 UTC, merged