Make the contextMenu in StructurePanel und in GalleryPanel identical
kitodo/kitodo-production pull request #4310
Opened 2021-03-26 20:54 UTC by IkramMaalej

Fixes #3646

2021-03-31 09:29 UTC, solth reviewed
This is a rather small technical change, but I believe it will help working with the metadata editor considerably! 👍 

Just one small nitpick: the context menu in the gallery does not disappear when clicking somewhere else, for example when selecting a different stripe:
<img width="794" alt="Bildschirmfoto 2021-03-31 um 11 29 15" src="https://user-images.githubusercontent.com/19183925/113122904-5d76cc80-9214-11eb-9bd4-57e99aeb73f0.png">

2021-03-31 09:29 UTC, solth commented on Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/AddDocStrucTypeDialog.java
> +                    dataEditor.getStructurePanel().setSelectedLogicalNode(selectedLogicalNode.getParent());
I am not sure about this line: I understand that the selected logical node must be set to the parent structure when a page is selected, but what happens when the user then clicks `Cancel`? Then the `selectedLogicalNode` in the `StructurePanel` is still set to the parent structure, even though that is not visible in the tree, where the page still seems to be selected.

2021-03-31 09:29 UTC, solth commented on Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/gallery.xhtml
> +                                     mediaContextMenu
```suggestion
                                     imagePreviewForm:mediaContextMenu
```
Shouldn't this have the `imagePreviewForm:` prefix like the other `update`s?

2021-03-31 09:29 UTC, solth commented on Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/logicalStructure.xhtml
> +            <f:actionListener binding="#{DataEditorForm.addDocStrucTypeDialog.preparePreselectedViews()}"/>
```suggestion
                     <f:actionListener binding="#{DataEditorForm.addDocStrucTypeDialog.preparePreselectedViews()}"/>
```

2021-04-07 13:43 UTC, Kathrin-Huber commented
please resolve conflicts

2021-04-14 09:41 UTC, solth requested changes
Just one little change to completely synchronize context menus in structure tree and gallery since #4319 has been merged in the meantime.

2021-04-14 09:41 UTC, solth commented on Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/gallery.xhtml
> +                            DataEditorForm.structurePanel.assignedSeveralTimes and DataEditorForm.selectedMedia.size() eq 1}"
```suggestion
                            rendered="#{DataEditorForm.structurePanel.assignableSeveralTimes and
                            DataEditorForm.selectedMedia.size() eq 1}"
```

2021-04-14 11:29 UTC, solth approved these changes

2021-04-20 05:39 UTC, merged