Bring back advanced pagination buttons
kitodo/kitodo-production pull request #4439
Opened 2021-05-27 16:27 UTC by matthias-ronge

Fixes #4175, fixes #4475

2021-05-31 09:02 UTC, Kathrin-Huber requested changes
Please put this branch on the preview system and let it check from a product owner

2021-05-31 10:49 UTC, matthias-ronge commented on Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/PaginationPanel.java
> +    public void noIncrement() {
See section [Paginierung für Fortgeschrittene](https://github.com/kitodo/kitodo-production/wiki/Paginieren#paginierung-f%C3%BCr-fortgeschrittene) in the wiki

2021-05-31 12:16 UTC, matthias-ronge commented
> Please put this branch on the preview system and let it check from a product owner

I don’t know how the test system is meant to be.

2021-06-01 14:16 UTC, solth commented
> > Please put this branch on the preview system and let it check from a product owner
> 
> I don’t know how the test system is meant to be.

@matthias-ronge @Kathrin-Huber I just merged this branch into the preview system. The changes can now be tested there.

2021-06-04 07:46 UTC, Kathrin-Huber commented
![paginierung](https://user-images.githubusercontent.com/22615787/120765529-9899c280-c519-11eb-9974-461956a14b2a.gif)

The buttons always add-on, is this expected behaviour?
If I want to change the input, it restores with the next button. (see gif)

2021-06-04 11:30 UTC, matthias-ronge commented
> The buttons always add-on, is this expected behaviour?

Yes.

> If I want to change the input, it restores with the next button. (see gif)

That shouldn't happen now any more. And, now it works on the currently highlighted selection (which is intentional):

![Animation](https://user-images.githubusercontent.com/3040657/120794741-e8d44d00-c538-11eb-95df-b6d870ac3ae1.gif)

2021-06-18 17:38 UTC, merged