#4638 fix nullpointer exception in user detail
kitodo/kitodo-production pull request #4639
Opened 2021-09-06 14:51 UTC by markusweigelt

When user detail/edit is opened we check if ldap server is not null.

If ldap server is null a helper message will be shown.

2021-09-07 08:02 UTC, solth commented
If you link your pull request to the issue mentioned in the title a la "Fixes #4638" in the description, the issue will be closed automatically once the pull request gets merged. (see https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue for details)

2021-09-07 09:34 UTC, Kathrin-Huber requested changes

2021-09-07 09:34 UTC, Kathrin-Huber commented on Kitodo/src/main/java/org/kitodo/production/services/data/LdapServerService.java
> +        if ( user.getLdapGroup().getLdapServer() == null) {
We use `Objects.isNull()` for nullChecks (see 5 lines above). It's a convention, and I would like to keep it consistent.
If this is a good idea can be discussed here: #4087

2021-09-07 09:34 UTC, Kathrin-Huber commented on Kitodo/src/main/java/org/kitodo/production/services/data/LdapServerService.java
> +            Helper.setMessage(Helper.getTranslation("noLdapServerAssignedToLdapGroup"));
My first intention was, that `Helper.setErrorMessage` should be used here, but it is also a regular message the lines above. 🤦 
Please change to errorMessage in both places, or open an issue and fix it in a separat PR (which would be the better way 😏  )

2021-09-07 12:22 UTC, markusweigelt commented
Changed null check using null check convention. To change log level of error messages issue #4645 is created.

2021-09-07 12:23 UTC, markusweigelt reviewed
Requested changes are resolved.

2021-09-08 05:59 UTC, Kathrin-Huber approved these changes

2021-09-08 05:59 UTC, merged