Fix order of thumbnails after drag'n'drop
kitodo/kitodo-production pull request #4826
Opened 2021-11-15 12:05 UTC by solth

Fixes #4820

2021-11-15 12:48 UTC, matthias-ronge requested changes
Thanks for the solution, but using streams feels overcomplicated to me for this task. Why not just declare a

```java
private static final Comparator<Pair<View, LogicalDivision>> SORT_BY_IMAGE_ORDER = Comparator
        .comparing(pair -> pair.getLeft().getPhysicalDivision().getOrder());
```
and then do a
```java
Collections.sort(viewsToBeMoved, SORT_BY_IMAGE_ORDER);
```

2021-11-15 12:48 UTC, matthias-ronge commented on Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/GalleryPanel.java
> +        viewsToBeMoved = viewsToBeMoved.stream().sorted(Comparator.comparing(p -> p.getLeft().getPhysicalDivision()
Coding guidelines discourage single letter variable names. Replace `p` with `pair`.

2021-11-15 12:52 UTC, solth commented
> Thanks for the solution, but using streams feels overcomplicated to me for this task. Why not just declare a
> 
> ```java
> private static final Comparator<Pair<View, LogicalDivision>> SORT_BY_IMAGE_ORDER = Comparator
>         .comparing(pair -> pair.getLeft().getPhysicalDivision().getOrder());
> ```
> 
> and then do a
> 
> ```java
> Collections.sort(viewsToBeMoved, SORT_BY_IMAGE_ORDER);
> ```

Isn't that just as complicated, if not even more so? You are just moving the Comparator to a constant (which is only used once anyway, so I don't the reason to make a constant/variable in the first place)

2021-11-15 14:34 UTC, matthias-ronge commented
Yes, that's subjective, I find it easier to read than to create a stream especially for sorting. The advantage of the constant is that it is only created once when the class is initialized, while the argument, as you defined it, is created every time the method is called.  
But it's enough for me if you replace the `p` with a `pair`.

2021-11-15 15:56 UTC, markusweigelt approved these changes

2021-11-16 08:13 UTC, solth commented
> The advantage of the constant is that it is only created once when the class is initialized, while the argument, as you defined it, is created every time the method is called.

Ok, that's a good reason to move the comparator to a constant! Even though the method is still not called very often (and therefore the comparator wouldn't be instantiated very often, either), in the metadata editor I take every optimization I can!

2021-11-16 10:56 UTC, matthias-ronge approved these changes

2021-11-16 15:06 UTC, oliver-stoehr approved these changes

2021-11-22 13:54 UTC, merged