Add delete metadata buttons
kitodo/kitodo-production pull request #4890
Opened 2021-12-17 12:07 UTC by IkramMaalej

2021-12-17 22:14 UTC, solth commented
Does this fix #4279?

2021-12-23 10:23 UTC, solth commented
I get a `PropertyNotFoundException` when deleting a metadata that I just added:

https://user-images.githubusercontent.com/19183925/147226550-58a8c650-8d69-49e8-bb23-0042d6c18632.mov

2022-01-07 16:55 UTC, solth requested changes
Just a first part of the review. Will test more later.

One problem I encountered was that when I add a metadata group (for example "Person") during process creation and then add individutal metadata entries (for example "Display name" and "Family name") to the new group, the second entry will replace the first if I didn't add any values to the entries yet:

https://user-images.githubusercontent.com/19183925/148578362-f4c39f6b-783f-4212-8b83-0b4279745bdd.mov

2022-01-07 16:55 UTC, solth commented on Kitodo/src/main/java/org/kitodo/production/forms/createprocess/CreateProcessForm.java
> +            if (Objects.nonNull(processMetadata.getSelectedMetadataTreeNode()) || Objects.isNull(addMetadataDialog.getAddableMetadata())) {
This line is probably too long

2022-01-07 16:55 UTC, solth commented on Kitodo/src/main/java/org/kitodo/production/forms/createprocess/CreateProcessForm.java
> +                    .map(SelectItem::getValue).collect(Collectors.toList()).contains(((ProcessDetail) treeNode.getData()).getMetadataID());
This line is probably too long

2022-01-07 16:55 UTC, solth commented on Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ProcessDetail.java
> +
Missing JavaDoc

2022-01-07 16:55 UTC, solth commented on Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ProcessDetail.java
> +    public abstract Collection<Metadata> getMetadata(boolean skipEmpty) throws InvalidMetadataValueException;
Missing JavaDoc

2022-01-07 16:55 UTC, solth commented on Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ProcessMetadata.java
> +     * Adds an empty table line with the given type.
What "given type"? This function does not appear to have parameters. Please update JavaDoc.

2022-01-07 16:55 UTC, solth commented on Kitodo/src/main/resources/messages/messages_de.properties
> +metadataDeleteNotAllowed=Metadaten ist in Regelsatz als 'Required' oder "alwaysShowing" konfiguriert
```suggestion
metadataDeleteNotAllowed=Metadatum ist in Regelsatz als 'Required' oder "alwaysShowing" konfiguriert
```

2022-01-07 16:55 UTC, solth commented on Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
> +    width: calc(50% - 4 * var(--default-half-size) - 93px - 39px);
```suggestion
    width: calc(50% - var(--default-double-size) - 132px);
```

2022-01-07 16:55 UTC, solth commented on Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
> +    width: calc(50% - var(--default-half-size) - 93px - 39px);
```suggestion
    width: calc(50% - var(--default-half-size) - 132px);
```

2022-01-10 12:55 UTC, matthias-ronge commented on Kitodo/src/main/resources/messages/messages_de.properties
> +metadataDeleteNotAllowed=Metadaten ist in Regelsatz als 'Required' oder "alwaysShowing" konfiguriert
_Metadatum ist im Regelsatz vorgegeben_

2022-01-10 12:56 UTC, matthias-ronge commented
Maybe this is because of `additionallySelectedFields` only contains the additionally selected field? When adding another sub-field, the metadata tree table is rebuilt and the first additionally selected field is no longer known. I think it is complicated to fix this

2022-02-09 07:47 UTC, andre-hohmann commented
### Summary
- #4279 -> is fixed
- #4457 -> is fixed
- #4468 -> is fixed
- #4465 -> **i cannot assess this problem with our current configuration**
- #4893 -> is fixed
- #4284 -> **is not fixed - see review below**

### Review
1. _4284_: The metadata group can be copied with its values, but when the metadata editor is closed and opened again, the copied metadata group is lost. When the process is validated an exception occurs - see below. 
2. _Add metadata during creation of process_:  If a metadata field is imported and the same metadata field is added manually to the imported metadata, the following behaviour occurs: The field is added behind the existing metadata field, but contains the value of the metadata field, which has been at this position before. The values of all following metadata fields are mixed up in the same way. 
If a metadata field is added, which is not shown in the list of the imported metadata, everything works fine. 
The goal should be that the metadata fields and its values should not be mixed up when existing metadata fields are added manually. 

### Exception message 4284
```
An error has occurred:
Date/time: 2022-02-09 08:27:09
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
User IP: 134.100.172.21
Request URI: /cePreview/pages/metadataEditor.jsf
Ajax request: Yes
Status code: 500
Exception type: class java.lang.NullPointerException
Exception message:
Exception UUID:
Stack trace:
java.lang.NullPointerException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737)
	at java.base/java.util.stream.FindOps$FindOp.evaluateParallel(FindOps.java:160)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:548)
	at org.kitodo.dataeditor.ruleset.NestedKeyView.retrieveOrCompute(NestedKeyView.java:468)
	at org.kitodo.dataeditor.ruleset.NestedKeyView.lambda$storeValues$3(NestedKeyView.java:460)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at org.kitodo.dataeditor.ruleset.NestedKeyView.storeValues(NestedKeyView.java:459)
	at org.kitodo.dataeditor.ruleset.NestedKeyView.createAuxiliaryTable(NestedKeyView.java:304)
	at org.kitodo.dataeditor.ruleset.NestedKeyView.getSortedVisibleMetadata(NestedKeyView.java:422)
	at org.kitodo.validation.metadata.MetadataValidation.checkForMandatoryQuantitiesOfTheMetadataRecursive(MetadataValidation.java:263)
	at org.kitodo.validation.metadata.MetadataValidation.checkMetadataRules(MetadataValidation.java:172)
	at org.kitodo.validation.metadata.MetadataValidation.validate(MetadataValidation.java:123)
	at org.kitodo.production.services.validation.MetadataValidationService.validate(MetadataValidationService.java:181)
	at org.kitodo.production.forms.dataeditor.DataEditorForm.validate(DataEditorForm.java:409)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.el.parser.AstValue.invoke(AstValue.java:246)
	at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:266)
	at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
	at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
	at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
	at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
	at org.apache.myfaces.view.facelets.el.ContextAwareTagMethodExpression.invoke(ContextAwareTagMethodExpression.java:96)
	at javax.faces.event.MethodExpressionActionListener.processAction(MethodExpressionActionListener.java:83)
	at javax.faces.event.ActionEvent.processListener(ActionEvent.java:58)
	at javax.faces.component.UIComponentBase.broadcast(UIComponentBase.java:429)
	at javax.faces.component.UICommand.broadcast(UICommand.java:103)
	at javax.faces.component.UIViewRoot._broadcastAll(UIViewRoot.java:1255)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:420)
	at javax.faces.component.UIViewRoot._process(UIViewRoot.java:1741)
	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:935)
	at org.apache.myfaces.lifecycle.InvokeApplicationExecutor.execute(InvokeApplicationExecutor.java:42)
	at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:195)
	at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:142)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:204)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.kitodo.production.servletfilter.EncodingFilter.doFilter(EncodingFilter.java:69)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.kitodo.production.security.SecurityObjectAccessFilter.doFilter(SecurityObjectAccessFilter.java:86)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFil [...]

2022-02-09 12:07 UTC, IkramMaalej commented
@andre-hohmann 
> 4284: The metadata group can be copied with its values, but when the metadata editor is closed and opened again, the copied metadata group is lost. 

Did you mean that the metadata editor is closed with 'Save & exit' button or with 'Exit' button?

2022-02-09 13:19 UTC, andre-hohmann commented
I mean 'Save & exit'. 

I guess you ask, because it works for you. Therefore i tested a bit and found out that it only happens, when the metadata fields are only added and not changed. 
When i add at least one character in one sub-field of the duplicated metadata group, the whole metadata group is saved correctly and is shown after opening the metadata editor again.

2022-02-11 11:45 UTC, IkramMaalej commented
@andre-hohmann 
> I mean 'Save & exit'.
> 
> I guess you ask, because it works for you. Therefore i tested a bit and found out that it only happens, when the metadata fields are only added and not changed. When i add at least one character in one sub-field of the duplicated metadata group, the whole metadata group is saved correctly and is shown after opening the metadata editor again.

What you have described above is the intended logic so far, because for storing the metadata  we are using an object that doesn't allow duplicates (2 identical objects). But if we now want to save duplicates, then we have to adjust the logic accordingly.

2022-02-11 12:15 UTC, andre-hohmann commented
I do not need duplicate objects, but i wanted to describe my observation. Usually, it is a bad sign, if (meta)data disappears.  Maybe some users copy some elements and want them to adjust later, ...

In such cases, it would be helpful to show a message. In this case for example: 
- `The duplicate metadata object is not saved when the editor closed`. 

Then it is clear that the following behaviour is intended.

2022-02-14 17:42 UTC, matthias-ronge commented
@IkramMaalej is right: The metadata is stored internally as a [set (in the mathematical sense)](https://en.wikipedia.org/wiki/Set_(mathematics)). A set is defined as that its elements have no order, and a set cannot contain the same element more than once. Java automatically applies these rules to the metadata. This means that all elements of the set are compared with each other, and if an element is identical to another, i.e. it occurs more than once, it is deduplicated. For metadata, that's absolutely fine if the same thing doesn't occur multiple times.

**The contract of the set does assure to you, that no metadata, that is not 100% identical, will ever be deleted.**

This is not a bug.

2022-02-14 18:08 UTC, andre-hohmann commented
@matthias-ronge : Thanks a lot for clarification. Then #4284 is solved, too. I do not know how to change the previous comments, but maybe that is the way to make the transparent discussions. 

Thus, from my point of view, everything in the PR works fine except of:  
- #4465, which i cannot assess.

2022-02-24 12:45 UTC, andre-hohmann approved these changes
https://github.com/kitodo/kitodo-production/issues/4465 is not assessed.

2022-02-28 12:42 UTC, merged