Add functional metadata for 'docType' metadata
kitodo/kitodo-production pull request #4906
Opened 2022-01-12 09:49 UTC by solth

Fixes #4863

2022-01-13 10:15 UTC, matthias-ronge requested changes
Please also update the example rulesets in `Kitodo/rulesets` directory. As I understand your comment, this is necessary. Or isn’t it?

2022-01-13 10:15 UTC, matthias-ronge commented on Kitodo/src/main/java/org/kitodo/production/helper/TempProcess.java
> +                        .stream().filter(m -> m.getKey().equals(doctypeMetadata.get(0))).findFirst();
Please rename `m` variable to a full name.

2022-01-13 10:15 UTC, matthias-ronge commented on Kitodo/src/main/java/org/kitodo/production/services/data/ImportService.java
> +        RulesetManagementInterface rulesetManagementInterface
Please don’t use `Interface` suffix on a variable name. I.e., `RulesetManagementInterface rulesetManagement = `…

2022-01-13 10:15 UTC, matthias-ronge commented on Kitodo/src/main/java/org/kitodo/production/services/data/ImportService.java
> +        return new ArrayList<>(rulesetManagementInterface.getFunctionalKeys(FunctionalMetadata.DOC_TYPE));
There is no need to copy the result to another list.

    return rulesetManagementInterface.getFunctionalKeys(FunctionalMetadata.DOC_TYPE);

To use along with `contains()` as I mentioned above.

2022-01-13 11:17 UTC, solth commented
@matthias-ronge thank you for the review. I implemented most of your requested changes, apart from the `<p>` tag in the java doc, because this was specifically how Codacy accepted it.

2022-01-14 08:19 UTC, matthias-ronge approved these changes

2022-02-02 08:11 UTC, merged