Explicitly load Saxon, without incurring any side impacts on the JVM
kitodo/kitodo-production pull request #5109
Opened 2022-04-28 12:13 UTC by matthias-ronge

Fixes #5108

2022-05-24 08:57 UTC, solth requested changes
Please rebase / resolve conflicts!

2022-07-05 07:53 UTC, Kathrin-Huber commented
still waiting for a rebase here

2022-07-05 09:55 UTC, matthias-ronge commented
Doesn’t work anymore

2022-09-02 09:29 UTC, henning-gerhardt commented on Kitodo-XML-SchemaConverter/pom.xml
> +            <version>${saxon.version}</version>
This should not necessary as the used version of a package is controlled in the global pom file.

2022-09-02 11:49 UTC, solth approved these changes
Tested changes with catalog import and it worked as before.

2022-09-03 07:35 UTC, merged