Fix action to remove symbolic links from home directory for selected processes
kitodo/kitodo-production pull request #5195
Opened 2022-06-07 12:22 UTC by thomaslow

Closes #4554 

Issue #4554 reports that the action `Remove link from home directory` is not working as expected. Currently, the action triggers code that only removes symbolic links in the `fertig/` subdirectory (configuration property `doneDirectory`) of a users home directory. Symbolic links of processes created via the action `Link within home directory` are not removed.

This pull request changes the behavior of this action to remove symbolic links for all selected process from the home directory of the current user.

This means that the previous behavior (removing symbolic links from the `fertig/` directory) can no longer be triggered by a user. If no longer needed, the corresponding code could be removed (which is not part of this pull request).

2022-06-08 13:36 UTC, henning-gerhardt commented
> The error should be gone now.

Thank you. I will test this as soon as possible.

> There was an old jsf statement that did not make sense, probably from 2.x times.

This could be possible.

2022-06-09 08:28 UTC, henning-gerhardt commented
Your latest change to this pull request did fix the appearing error message. Works for me now without an issue.

2022-06-23 09:38 UTC, Kathrin-Huber requested changes

2022-06-23 09:38 UTC, Kathrin-Huber commented on Kitodo/src/main/resources/messages/messages_de.properties
> +directoryRemovedSelected=Alle ausgewählten Verzeichnisse aus Benutzerhome entfernt
```suggestion
directoryRemovedSelected=Alle ausgew\u00E4hlten Verzeichnisse aus Benutzerhome entfernt
```

please encode

2022-06-23 11:01 UTC, merged