Added Spanish translation files of the messages
kitodo/kitodo-production pull request #5214
Opened 2022-07-04 09:17 UTC by joergleh

Fixes #5033

2022-07-05 10:43 UTC, henning-gerhardt commented
One question to the current (@Kathrin-Huber) and new (@solth) release management: if Spanish translation is merged must we provide Spanish translation (add or update) changes as well in future pull requests?

2022-07-05 12:43 UTC, solth commented
> I will then provide the translations into Spanish once I am able to notice what has been changed.

@joergleh Thank you very much providing the Spanish translation files and for offering to update them when changes are made to the other language files.

I don't know if Github natively provides tools to automatically get informed about changes to specific files (like `messages_de.properties` or `messages_es.properties`, in this case) but there seems to be a third party tool specifically for that purpose: https://app.github-file-watcher.com/
I have never used this "github file watcher" myself so I do not know if it works or is secure, but perhaps someone else has expieriences with that app?

2022-07-05 12:57 UTC, henning-gerhardt requested changes
You must at least extend the file [faces-config.xml](https://github.com/kitodo/kitodo-production/blob/master/Kitodo/src/main/webapp/WEB-INF/faces-config.xml) for spanish as without this there is no possibility to switch the language.

I'm surprised that Spanish umlauts must not be translated in some ugly to read encoding like in the German translation, so I don't know if this is working on every system properly.

2022-07-05 12:59 UTC, henning-gerhardt commented
> It would suffice if you change the Spanish translation files accordingly to the German and English ones; I will then provide the translations into Spanish once I am able to notice what has been changed.

Thank you for this offering / submission as the main translation too!

2022-07-05 13:57 UTC, matthias-ronge commented on Kitodo/src/main/resources/messages/messages_es.properties
> +correctionK=K
Should be
`correctionK=C`
(first letter of `Corrección`)

2022-07-06 13:11 UTC, Kathrin-Huber approved these changes

2022-07-06 13:46 UTC, merged