Enable parentMappingFile configuration for catalog search configurations
kitodo/kitodo-production pull request #5310
Opened 2022-08-20 12:00 UTC by solth

Fixes #5305

2022-08-22 13:07 UTC, andre-hohmann commented
@solth : Thanks for the PR. Technically, the first tests are successful! I can now create hierarchical processes with the parent mapping file. 

However, i have observed a minor error: There are process identifier displayed to enable the selection the process to modify its metadata. 
But instead of the superordinate process' identifier, it is shown the language label `ger`. Instead of `ger`, the identifier `GA03538-00448249` should be displayed. 

In the metadata and in the process title, the values are correct. This it seems to be rather a problem of display then a problem of functionality. 
For the K10plus catalogue, the identifier are shown correctly. 

![FehlerHierarchie01](https://user-images.githubusercontent.com/14835770/185927085-dd48f545-620c-472d-aa4c-a4307b8cf94b.jpg)

2022-08-22 13:11 UTC, henning-gerhardt requested changes
Changes looks good and are working but the possibility to use the translation system for the tool tip is missing - aside of missing automatic executed tests.

2022-08-23 07:47 UTC, andre-hohmann commented
@solth : With the new fix, the "ger-problem" is solved. 
Thus, My tests are successful!

2022-08-23 07:52 UTC, henning-gerhardt approved these changes

2022-08-23 09:02 UTC, merged