Add Kitodo Script to set labels automatically
kitodo/kitodo-production pull request #5334
Opened 2022-08-30 08:28 UTC by matthias-ronge

Resolves #5016

2022-08-30 08:45 UTC, henning-gerhardt commented on Kitodo/src/main/java/org/kitodo/production/services/command/KitodoScriptService.java
> +import org.apache.logging.log4j.util.Strings;
I would prefer the `isEmpty` method from `StringUtils` class of the `apache-commons`.`lang3` package (or the old lang package if the old package should be used future and replacement is not planed in near future)  instead a string checking method from Log4J.

2022-11-08 14:39 UTC, matthias-ronge commented
Rebased

2022-11-29 09:54 UTC, solth commented
Please rebase against master to fix broken Github CI builds!

2023-01-10 09:22 UTC, henning-gerhardt requested changes
Please add tests to prove your changes are correct implemented.

2023-02-28 08:40 UTC, matthias-ronge commented
Can be solved by XSLT.

2023-02-28 08:40 UTC, closed without merging