Improve "correction K" tooltip
kitodo/kitodo-production pull request #5403
Opened 2022-10-17 15:39 UTC by oliver-stoehr

The tooltip is now rendered using `p:tooltip` and also lists all normal comments in addition to the correction comments.
Correction comments in the tooltip are marked with a `K`/`C` in red (not yet resolved) or grey (already resolved).
<img width="798" alt="Screenshot of improved tooltip" src="https://user-images.githubusercontent.com/32509444/196221126-2a73d1bd-0135-434a-b397-92910da9cd58.png">

The column is renamed from "Correction message" to "Comments".
It can now display three different symbols:
- a grey speech bubble for normal comments
- a red `K`/`C` for an unresolved correction comment
- a grey `K`/`C` for at least one resolved correction comment
![Bildschirmfoto 2022-10-18 um 14 26 24](https://user-images.githubusercontent.com/32509444/196430688-258b1b26-54e2-4a66-b31a-962ac0b3d4ea.png)

Resolves #4994.

2022-10-18 12:49 UTC, thomaslow commented
This will create substantial merge conflicts with #5360, which stores the comment status in ElasticSearch to be sortable.

2022-10-25 12:12 UTC, solth commented
#5360 has been merged. Please resolve resulting conflicts.

2022-11-29 09:17 UTC, solth commented
Please rebase against master to fix broken Github CI builds!

2022-12-09 11:00 UTC, thomaslow commented
@oliver-stoehr 
I tested your pull request. Functionally, it seems to work just fine and resolves the conflicts mentioned earlier. From this perspective, the pull request is acceptable. 

However, I do have some performance concerns. When rendering a process list with 100 processes, the performance of the backend call that retrieves the DataTable contents (inspected via the F12 browser network tab) degrades from ~0.8 seconds (current master) to ~1.3 seconds. It is not a huge deal, but noticable. Still, in my database I only have in total ~8 comments. I could imagine, if there are more comments in your database, performance might be affected even more.

I suspect the performance degradation is caused by multiple calls to `ProcessForm.getComments(process)` in `processList.xhtml`, which each will trigger additional 100 database queries to find all comments of all listed processes. Unfortunately, theses database queries are also not cached in Kitodo. So, two calls to `ProcessForm.getComments(process)` will trigger 200 database queries. Maybe it is possible to improve the code to save one or two calls or even write a custom database query that retrieves all comments with a single database query? For example, you could create a RequestScoped bean that issues the custom database query and caches the comments during the lifetime of the request (and potentially multiple calls to the bean getter method when rendering the jsf).

Ideally, since the comments are not even shown to the user without hovering over the comment symbol, the tooltip contents could be loaded only when hovering occurs, instead of pre-loading all comments of all listed processes. Unfortunately, the Primefaces Tooltip component doesn't seem to support this.

2022-12-19 16:49 UTC, oliver-stoehr commented
Thank you for pointing out! I moved the `getComments` methods to a separate bean which caches the comments per request. So there should now be only one database query per process.  
The comment icon's `rendered` attribute now relies on index information and does not query the database. Same applies to processes without comments.

2023-01-18 21:17 UTC, solth commented
@thomaslow could you finish your review for this pull request and check whether your prior remarks have been incorporated sufficiently?

2023-01-19 08:44 UTC, thomaslow commented
Sorry. As I said in November, I really do not have any more time left for Kitodo. The review above was already made as a favor to the community.

2023-01-19 13:35 UTC, solth commented
@thomaslow sure, I understand no problem. Thanks for the initial review, though!

2023-01-19 13:46 UTC, solth requested changes
Please rename the SQL migration file because "V2_117..." already exists.

2023-01-19 13:46 UTC, solth commented on Kitodo/src/main/java/org/kitodo/production/forms/CurrentTaskForm.java
> +import java.util.Collections;
```suggestion
```
It seems this import is no longer required

2023-01-19 13:46 UTC, solth commented on Kitodo/src/main/java/org/kitodo/production/forms/CurrentTaskForm.java
> +import org.kitodo.data.database.beans.Comment;
```suggestion
```
It seems this import is no longer required

2023-01-19 13:46 UTC, solth commented on Kitodo/src/main/java/org/kitodo/production/forms/DesktopForm.java
> +import java.util.Collections;
```suggestion
```
It seems this import is no longer required

2023-01-19 13:46 UTC, solth commented on Kitodo/src/main/java/org/kitodo/production/forms/DesktopForm.java
> +import org.kitodo.data.database.beans.Comment;
```suggestion
```
It seems this import is no longer required

2023-01-19 13:46 UTC, solth commented on Kitodo/src/main/java/org/kitodo/production/forms/ProcessForm.java
> +import java.util.Collections;
```suggestion
```
It seems this import is no longer required

2023-01-19 13:46 UTC, solth commented on Kitodo/src/main/java/org/kitodo/production/forms/ProcessForm.java
> +import org.kitodo.data.database.beans.Comment;
```suggestion
```
It seems this import is no longer required

2023-01-24 18:13 UTC, solth approved these changes

2023-02-06 13:43 UTC, merged