Add help text
kitodo/kitodo-production pull request #5426
Opened 2022-11-01 10:53 UTC by IkramMaalej

Fixes #3478

2022-11-03 14:24 UTC, andre-hohmann requested changes
I am not a fan of links behind the words "Here" or "Hier". For me, it is more appropriate to use the label of the page to which the link aims.
 
- In der [Anwenderdokumentation Kitodo.Production 3.X](https://github.com/kitodo/kitodo-production/wiki/Anwenderdokumentation-Kitodo.Production-3.X) finden Sie Bedienungshinweise für Kitodo.Production 3.x.
- You will find instructions for Kitodo.Production 3.x in the [Kitodo.Production 3.X
user documentation](https://github.com/kitodo/kitodo-production/wiki/Anwenderdokumentation-Kitodo.Production-3.X). 

Is there a reason to apply the link to the words "Hier" or "Here"?

2022-11-21 12:53 UTC, andre-hohmann approved these changes
@IkramMaalej : Perfect ;-) Thanks a lot! 
from my point of view, the issue is solved.

2022-11-21 12:57 UTC, henning-gerhardt approved these changes

2022-11-29 09:17 UTC, solth commented
Please rebase against master to fix broken Github CI builds!

2022-11-30 10:05 UTC, merged