Add interactive filter menu
kitodo/kitodo-production pull request #5523
Opened 2023-01-30 20:52 UTC by oliver-stoehr

This pull requests adds a more interactive filter menu to the process, task and user lists based on #5212.
A new overlay will open on focus of the filter input and close on blur. This overlay contains the filters that were previously located at the bottom of each list. It will also provide suggestions for the filters when applicable. 
![Bildschirm­foto 2023-01-30 um 21 36 33](https://user-images.githubusercontent.com/32509444/215590777-a92ef300-c0a7-41d0-8a4e-9a600b52f3a0.png)
These suggestions are filtered by the text the user enters into the input.
The overlay will suggest filter categories and also filter values for the following filter categories:
- step
- stepdone
- stepinwork
- steplocked
- stepopen
- stepdonetitle
- project
- property
The suggestions can be selected by mouse and keyboard (up, down, enter). 
Submitted filters are displayed in a more distinguishable way and can be removed by clicking the "x" or pressing delete key in the filter input:
![Bildschirm­foto 2023-01-30 um 21 48 58](https://user-images.githubusercontent.com/32509444/215591706-852e9b9c-41b0-43c5-a8cc-55b312ddff31.png)

Resolves #5212.

2023-02-03 08:27 UTC, henning-gerhardt requested changes
This is only a code review of Java classes and a little bit of css / xhtml files. I did not into the JavaScript changes nor did a deep look into the css and xhtml files as my knowledge there is a little above zero.

2023-02-03 08:27 UTC, henning-gerhardt commented on Kitodo/src/main/webapp/WEB-INF/templates/includes/processes/filterMenu.xhtml
> +</ui:composition>
Missing new line at end of file.

2023-02-03 08:27 UTC, henning-gerhardt commented on Kitodo/src/main/webapp/WEB-INF/templates/includes/tasks/filterMenu.xhtml
> +</ui:composition>
Missing new line at end of file.

2023-02-03 08:27 UTC, henning-gerhardt commented on Kitodo/src/main/webapp/WEB-INF/templates/includes/users/filterMenu.xhtml
> +</ui:composition>
Missing new line at end of file.

2023-02-03 08:27 UTC, henning-gerhardt commented on Kitodo/src/main/java/org/kitodo/production/filters/ParsedFilter.java
> +        if (o == null || getClass() != o.getClass()) {
Replace `o === null` with `Objects.isNull(o)`  and the second part of the condition looks wierd. It is comparing the return of `getClass()` of the current class which is the class itself and compare it to the class from the given class. The comparing itself is maybe done by calling the `equals()` method of on of both classes? But I'm not an expert for writing equals() methods.

2023-02-03 08:27 UTC, henning-gerhardt commented on Kitodo/src/main/java/org/kitodo/production/filters/ParsedFilter.java
> +    public boolean isOr() {
Method never used or I did not found an usage of this method. If so, remove it as it is not implemented yet.

2023-02-03 08:27 UTC, henning-gerhardt commented on Kitodo/src/main/java/org/kitodo/production/services/data/TaskService.java
> +        return findDistinctValues(QueryBuilders.matchAllQuery(), "title.keyword", true, countDatabaseRows()); // TODO nur template tasks?
If this comment still valid? If yes why is this not be decided while developing this?

2023-02-03 08:27 UTC, henning-gerhardt commented on Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
> +    z-index: 1; /* TODO remove when not needed */
Who can decide if this is still needed?

2023-02-03 08:27 UTC, henning-gerhardt commented on Kitodo/src/main/webapp/WEB-INF/resources/css/kitodo.css
> +    position: relative; /* TODO kann das weg? */
A TODO in German language. Maybe do the decision or at least translate it.

2023-02-06 11:56 UTC, oliver-stoehr commented
@subhhwendt can you please provide the "property" filter that produced an error? I will look into this.
This might be an error that already exists without this pull request, see #5530.

2023-02-08 14:24 UTC, andre-hohmann approved these changes
@oliver-stoehr : as discussed before, here is just a rough estimate. 
The main point is that Issue #3511 is solved. I have already sent you some suggestions for improvement by mail as a preliminary review. 
Let me know if further assessment is needed.

2023-02-21 15:18 UTC, solth commented
@oliver-stoehr please rebase against current master to resolve conflicts as this pull request is the next merge candidate.

2023-02-22 08:14 UTC, henning-gerhardt commented
@solth : as I wrote 3 weeks ago: "This is only a code review of Java classes and a little bit of css / xhtml files. I did not into the JavaScript changes nor did a deep look into the css and xhtml files as my knowledge there is a little above zero." .. I can and I will not approve a pull request where only parts reviewed by me and / or I only know the requirements of the change. If you need somebody who is full reviewing this change then please assign the review to an other person than me.

2023-02-22 15:56 UTC, markusweigelt requested changes
Great work! Test your implementation with process, task and user filter and it works as far as possible.

However, a out of bounds exception appears with some filter strings. e.g. when I navigate to processes and select "property" from suggestions and press "enter". 
```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.kitodo.production.services.data.FilterService.createProcessPropertyFilter(FilterService.java:527)
	at org.kitodo.production.services.data.FilterService.buildQueryFromCondition(FilterService.java:252)
	at org.kitodo.production.services.data.FilterService.queryBuilder(FilterService.java:196)
	at org.kitodo.production.helper.SearchResultGeneration.getQueryForFilter(SearchResultGeneration.java:85)
	at org.kitodo.production.services.data.ProcessService.getQueryForFilter(ProcessService.java:409)
	at org.kitodo.production.forms.ProcessForm.getAmount(ProcessForm.java:1100)
	at jdk.internal.reflect.GeneratedMethodAccessor595.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:85)
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:62)
	at org.apache.myfaces.el.unified.resolver.FacesCompositeELResolver.getValue(FacesCompositeELResolver.java:179)
	at org.apache.el.parser.AstValue.getValue(AstValue.java:168)
	at org.apache.el.parser.AstDeferredExpression.getValue(AstDeferredExpression.java:42)
	at org.apache.el.parser.AstCompositeExpression.getValue(AstCompositeExpression.java:48)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:189)
	at org.jboss.weld.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
	at org.jboss.weld.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:93)
	at javax.faces.component._DeltaStateHelper.eval(_DeltaStateHelper.java:356)
	at javax.faces.component.UIOutput.getValue(UIOutput.java:67)
	at org.apache.myfaces.shared.renderkit.RendererUtils.getValue(RendererUtils.java:486)
	at org.apache.myfaces.shared.renderkit.RendererUtils.getStringValue(RendererUtils.java:329)
	at org.apache.myfaces.shared.renderkit.html.HtmlTextRendererBase.renderOutput(HtmlTextRendererBase.java:94)
	at org.apache.myfaces.shared.renderkit.html.HtmlTextRendererBase.encodeEnd(HtmlTextRendererBase.java:81)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:675)
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:555)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl$PhaseAwareVisitCallback.processRenderComponent(PartialViewContextImpl.java:826)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:787)
	at org.apache.myfaces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:213)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1019)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1047)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1047)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1047)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1047)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartialRendering(PartialViewContextImpl.java:518)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:420)
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65)
	at javax.faces.context.PartialViewContextWrapper.processPartial(PartialViewContextWrapper.java:97)
	at org.omnifaces.context.OmniPartialViewContext.processPartial(OmniPartialViewContext.java:122)
	at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:571)
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:542)
	at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.renderView(FaceletViewDeclarationLanguage.java:1897)
	at org.apache.myfaces.application.ViewHandlerImpl.renderView(ViewHandlerImpl.java:315)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:73)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:73)
	at org.omnifaces.viewhandler.OmniViewHandler.renderView(OmniViewHandler.java:151)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:73)
	at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:122)
	at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:266)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:206)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.kitodo.production.servletfilter.EncodingFilter.doFilter(EncodingFilter.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.omnifaces.filter.GzipResponseFilter.doFilter(GzipResponseFilter.java:183)
	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:337)
	at org.kitodo.production.security.SecurityObjectAccessFilter.doFilter(SecurityObjectAccessFilter.java:89)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:109)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security. [...]

2023-03-03 14:31 UTC, markusweigelt requested changes
Thx. Under users i still get the same in `ArrayIndexOutOfBoundsException`.

```
KITODO.PRODUCTION Version 3.6.0-SNAPSHOTEs ist ein Fehler aufgetreten:
Date/time: 2023-03-03 15:21:05
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
User IP: 172.21.0.1
Request URI: /kitodo/pages/users.jsf
Ajax request: No
Status code: 500
Exception type: class java.lang.ArrayIndexOutOfBoundsException
Exception message: Index 1 out of bounds for length 1
Exception UUID:
Stack trace:
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.kitodo.production.services.data.FilterService.getSQLFilterMap(FilterService.java:1042)
	at org.kitodo.production.services.data.UserService.countResults(UserService.java:104)
	at org.kitodo.production.model.LazyDTOModel.load(LazyDTOModel.java:105)
	at org.primefaces.component.datatable.DataTable.loadLazyData(DataTable.java:567)
	at org.primefaces.component.datatable.DataTableRenderer.preRender(DataTableRenderer.java:130)
	at org.primefaces.component.datatable.DataTableRenderer.encodeEnd(DataTableRenderer.java:93)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:675)
	at javax.faces.component.UIData.encodeEnd(UIData.java:1835)
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:555)
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:551)
	at org.primefaces.component.tabview.TabViewRenderer.encodeTabContent(TabViewRenderer.java:301)
	at org.primefaces.component.tabview.TabViewRenderer.lambda$encodeContents$1(TabViewRenderer.java:277)
	at org.primefaces.component.tabview.TabView.forEachTab(TabView.java:186)
	at org.primefaces.component.tabview.TabViewRenderer.encodeContents(TabViewRenderer.java:275)
	at org.primefaces.component.tabview.TabViewRenderer.encodeMarkup(TabViewRenderer.java:144)
	at org.primefaces.component.tabview.TabViewRenderer.encodeEnd(TabViewRenderer.java:83)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:675)
	at org.primefaces.renderkit.CoreRenderer.renderChild(CoreRenderer.java:88)
	at org.primefaces.renderkit.CoreRenderer.renderChildren(CoreRenderer.java:70)
	at org.primefaces.component.panel.PanelRenderer.encodeContent(PanelRenderer.java:219)
	at org.primefaces.component.panel.PanelRenderer.encodeMarkup(PanelRenderer.java:133)
	at org.primefaces.component.panel.PanelRenderer.encodeEnd(PanelRenderer.java:68)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:675)
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:555)
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:551)
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:551)
	at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.renderView(FaceletViewDeclarationLanguage.java:1897)
	at org.apache.myfaces.application.ViewHandlerImpl.renderView(ViewHandlerImpl.java:315)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:73)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:73)
	at org.omnifaces.viewhandler.OmniViewHandler.renderView(OmniViewHandler.java:151)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:73)
	at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:122)
	at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:266)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:206)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.kitodo.production.servletfilter.EncodingFilter.doFilter(EncodingFilter.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.omnifaces.filter.GzipResponseFilter.doFilter(GzipResponseFilter.java:183)
	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:337)
	at org.kitodo.production.security.SecurityObjectAccessFilter.doFilter(SecurityObjectAccessFilter.java:89)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:109)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:147)
	at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:125)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:223)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilt [...]

2023-03-13 11:13 UTC, oliver-stoehr commented
I improved the layout so the parsed filters should always be visible now. They will still overflow the input field, when there is not enough space. I would like to move the general solution for this overflow to another pull request as I'm not yet sure about the best way to solve this.

I was not able to reproduce the `ArrayIndexOutOfBoundsException`. If it still can be reproduced, I would like to address this in a new issue/pr since this is an existing bug in the filters and does not depend on the changes of this pull request.

@markusweigelt could you review my latest changes?

2023-03-13 13:51 UTC, markusweigelt approved these changes
Thx works for me! 

I could not recreate the `ArrayIndexOutOfBoundsException` with various tests either. :thinking:

2023-03-13 14:04 UTC, merged