Add metadata in calendar to one specific issue
kitodo/kitodo-production pull request #5526
Opened 2023-02-03 11:34 UTC by oliver-stoehr

This pull requests adds a new button to the calendar day dialog. With this button metadata can be added to one specific issue.
For example this allows to add metadata only to the daily occurring "morning issue" without adding the metadata also to the daily occurring "evening issue".

Resolves #5106.

2023-02-06 10:10 UTC, andre-hohmann approved these changes
It is possible to create processes for several issues per day which can be labelled separately according to the issuance, as for example: 
- Morning edition
- Evening edition
- Special edition

Thus, from the user perspective, it works and the issue #5106 is resolved.

2023-02-22 10:15 UTC, henning-gerhardt commented on Kitodo/src/main/java/org/kitodo/production/model/bibliography/course/metadata/CountableMetadata.java
> +                        && (issue == null && this.delete == null || issue.equals(this.delete)));
If it is possible replace null comparing with Objects.isNull() or Objects.nonNull() method calls.

2023-02-22 10:16 UTC, henning-gerhardt commented on Kitodo/src/test/java/org/kitodo/selenium/testframework/pages/ProcessesPage.java.orig
> +/*
Is this file needed. Looks like a local backup of a later modified file. Remove this file if its not needed anymore.

2023-02-27 13:28 UTC, henning-gerhardt requested changes
A licence header is now missing.

2023-02-27 13:28 UTC, henning-gerhardt commented on Kitodo/src/test/java/org/kitodo/selenium/testframework/pages/CalendarPage.java
> +package org.kitodo.selenium.testframework.pages;
Missing licence header

2023-02-27 13:51 UTC, henning-gerhardt approved these changes

2023-02-27 18:21 UTC, merged