Skip automatic removal of missing media from workpiece, when no media…
kitodo/kitodo-production pull request #5598
Opened 2023-03-15 15:23 UTC by markusweigelt

… was found, Fix some potential npes

2023-03-15 15:33 UTC, markusweigelt commented
@henning-gerhardt 

> At least, there should be a message that includes an explicit request for the user to delete the references. If this is not confirmed, the references remain. This message must be worded very clearly to avoid accidental wrong selection.

With the current implementation of this pr, the references are not remove and only a warning message is shown what happend.
Is it necessary to show a dialog to select loading behaviour.  I think it can be very annoying and may also lead to user errors. What do you think? Does the problem occur not so often and the selection errors are negligible (cause you can reload metadataeditor if you select the wrong loading behaviour if the user notices it)?

2023-03-16 06:44 UTC, andre-hohmann commented
@markusweigelt : Thanks a lot!

A warning without a dialog function is absolutely sufficient. If someone needs a dialog function, this can be developed supplementary. 

Unfortunately, it is difficult to estimate how often certain cases occur in the respective facilities. The discussion following  https://github.com/kitodo/kitodo-production/issues/5579#issuecomment-1460308477 confirms in my opinion, that your suggestion is the best way to solve the basic problem (removal of needed references) with little effort. 

Especially https://github.com/kitodo/kitodo-production/issues/5579#issuecomment-1466264052 shows that there are probably no use cases in which the removal of references is needed.

2023-03-16 09:37 UTC, henning-gerhardt requested changes
This is a code only review. Functionality check will be performed later. Maybe adding tests should help here and prevent changes in future in a bad way.

2023-03-16 09:37 UTC, henning-gerhardt commented on Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/StructurePanel.java
> +            return null;
According to Coding Guidelines returning `null` value should be avoided. There are a few places in the source code where an additionl null check must be added and not only at the one place later in this pull request.

According to my IDE (IntelliJ IDEA) the return statement here should be written as `return Optional.empty()`.

2023-03-16 09:37 UTC, henning-gerhardt commented on Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/StructurePanel.java
> +            return null;
See comment above.

2023-03-16 09:37 UTC, henning-gerhardt commented on Kitodo/src/main/java/org/kitodo/production/services/command/KitodoScriptService.java
> +                return executeRemainingScript(processes);
Change is not related to the issue. Please revert this and open a separate pull request for this change.

2023-03-16 09:37 UTC, henning-gerhardt commented on Kitodo/src/main/java/org/kitodo/production/services/command/KitodoScriptService.java
> +    private boolean executeRemainingScript(List<Process> processes)
See comment above. Removing of the unused parameter is a separate issue.

2023-03-16 09:37 UTC, henning-gerhardt commented on Kitodo/src/main/java/org/kitodo/production/services/dataeditor/DataEditorService.java
> +        if (Objects.nonNull(selectedStructure) && selectedStructure.isPresent()) {
The null check could be avoided if the `getSelectedStructure()` method is changed in the already mentioned way (`return null` -> `return Optional.empty()`.

2023-03-16 11:59 UTC, markusweigelt commented
> Especially [#5579 (comment)](https://github.com/kitodo/kitodo-production/issues/5579#issuecomment-1466264052) shows that there are probably no use cases in which the removal of references is needed.

Maybe it makes more sense to take out the deletion directly than to introduce this distinction. Alternatively we could also add a project option to clean up the file references which is turned off by default or a button in metadataeditor to do it manually.

Who decides here if this is still needed?

2023-03-22 15:15 UTC, andre-hohmann commented
@markusweigelt : Thanks a lot for the PR. I had a look on it and it works!
The only thing I noticed is that when the language is set to English, the message in German language is displayed. 
It's not "bad" and maybe it's just because of our configuration. Nevertheless, I want to draw attention to it.

2023-03-22 15:18 UTC, henning-gerhardt approved these changes
Changes looks nice and clean and adding a test is very nice.

Why the German warn message appears but the interface is set in English is unclear and maybe not related to the changes itself.

2023-03-23 16:19 UTC, merged