Log a helpful message
kitodo/kitodo-production pull request #5633
Opened 2023-04-21 08:15 UTC by matthias-ronge

The error message "Some top level structure elements in the current ruleset are missing functional metadata of type 'recordIdentifier' which is required for OPAC import!" can be hard to debug. This patch adds logging of additional helpful messages. The control flow is changed so that in case of error, all error cases are found and logged, not just the first one.

Example of log:

```
[ERROR] 2023-04-21 10:13:14.011 [http-nio-8080-exec-10] ImportService - Division 'Article' allows no metadata for use 'recordIdentifier': None of [CatalogIDDigital] in allowed metadata keys [LABEL, ORDERLABEL, TitleDocMain, TitleDocSub, Person].
[ERROR] 2023-04-21 10:13:14.069 [http-nio-8080-exec-10] ImportService - Division 'Chapter' allows no metadata for use 'recordIdentifier': None of [CatalogIDDigital] in allowed metadata keys [LABEL, ORDERLABEL, TitleDocMain, TitleDocSub, Person].
[ERROR] 2023-04-21 10:13:14.102 [http-nio-8080-exec-10] ImportService - Division 'Provenance' allows no metadata for use 'recordIdentifier': None of [CatalogIDDigital] in allowed metadata keys [LABEL, ORDERLABEL, TitleDocMain, TitleDocSub, Person].
```

2023-04-21 09:29 UTC, henning-gerhardt commented
@matthias-ronge : Where is the message `Some top level structure elements in the current ruleset are missing functional metadata of type 'recordIdentifier' which is required for OPAC import!` created? I did not see any change of this message in your changes? You only add a backend logging for this error case.

2023-04-26 13:42 UTC, matthias-ronge commented
The message appears from the [recordIdentifierMissingDialog.xhtml, l. 30](https://github.com/kitodo/kitodo-production/blob/master/Kitodo/src/main/webapp/WEB-INF/templates/includes/recordIdentifierMissingDialog.xhtml#L30). At the moment I'm not sure how I can bring the message from `ImportService.isRecordIdentifierMetadataConfigured()` into this dialog.

2023-05-16 08:06 UTC, solth requested changes
@matthias-ronge thanks for adding information about the specific metadata and divisions to the popup dialog. I am sure this will make fixing incorrectly configured rulesets much easier. 

The layout of the dialog could probably be improved to make it easier to read, but that can also be done in a separate Pull Request: 

<img width="701" alt="Bildschirmfoto 2023-05-16 um 09 26 11" src="https://github.com/kitodo/kitodo-production/assets/19183925/b949f60e-1918-4c15-911e-40b305677bd6">

There are however a few other points that need to be discussed, that you can find below.

2023-05-16 09:04 UTC, matthias-ronge commented on Kitodo/src/main/java/org/kitodo/exceptions/RecordIdentifierMissingDetail.java
> +     * <b>Constructor.</b><!-- --> Builds a new data object to store details
Javadoc copies the “first sentence” of the method description to the method summary table. The first sentence is recognized by the dot, followed by new-line or space. (That is why checkstyle complains if there is no dot in the javadoc.) This is a common way to “ignore” a dot.

    /**
     * <b>Constructor.</b><!-- --> Lorem ipsum. Dolor sit amet.

Shows in the summary as: “**Constructor.** Lorem ipsum.”

    /**
     * <b>Constructor.</b> Lorem ipsum. Dolor sit amet.

Shows in the summary as: “**Constructor.**”

I like putting the “<b>Constructor.</b><!-- --> ” in front of constructor Javadoc, it feel it makes it better readable. But we can leave it off if you dislike it.

2023-05-16 09:05 UTC, matthias-ronge commented on Kitodo/src/main/java/org/kitodo/exceptions/RecordIdentifierMissingDetail.java
> +     * Returns the division of the detail of the missing disc identifier.
Yeah, the debt of using translate. 😿

2023-05-16 09:48 UTC, henning-gerhardt commented on Kitodo/src/main/java/org/kitodo/production/security/SecurityConfig.java
I'm currently working on refactoring this big method in this class.

2023-05-17 09:26 UTC, matthias-ronge commented
@solth Bei mir läuft der SearchingST lokal ohne Probleme durch. Keine Ahnung warum das da hängt

2023-05-19 07:24 UTC, solth commented
> Bei mir läuft der SearchingST lokal ohne Probleme durch. Keine Ahnung warum das da hängt

Ja, SearchingST scheint derzeit sehr unzuverlässig durchzulaufen. Das ist mir bei anderen PRs auch schon aufgefallen. Nach ein paar Versuchen klappt es dann aber meisten, so wie scheinbar auch hier nun.

2023-05-23 08:30 UTC, solth requested changes
Thanks a lot for the adjustments. Just some unused imports left and a few suggestions on how to easily improve the layout/design of the popup dialog (not sure if the red cross on orange background is a good idea, though; should probably be replaced by a similar icon with a darker color to improve readability)

<img width="621" alt="Bildschirmfoto 2023-05-23 um 10 25 32" src="https://github.com/kitodo/kitodo-production/assets/19183925/5aaeea86-1c18-4573-9da0-078014e218f6">

As you can see in the screenshot I also replaced `MetadataViewInterface::getKey` with `MetadataViewInterface::getLabel` in `RecordIdentifierMissingDetail.java`, line 47 and `divisionView.getKey()` with `divisionView.getLabel()` in `ImportService.java`, line 1380 - after unused imports have been removed - to display information the user is probably more familiar with. 

I think we should generally stick to showing ruleset labels instead of keys in the frontend because that is was the normal user will see most of the time when creating processes or using the metadata editor.

2023-05-23 08:30 UTC, solth commented on Kitodo/src/main/webapp/WEB-INF/templates/includes/recordIdentifierMissingDialog.xhtml
Could you also increase the `width` of this dialog a little bit to something like `600px` or `680px` since it contains a lot of text?

2023-05-23 13:46 UTC, solth approved these changes

2023-05-23 14:20 UTC, merged