Fix thumbnail scrolling
kitodo/kitodo-production pull request #5672
Opened 2023-05-30 13:10 UTC by markusweigelt

- Change refreshing element
- Adapt the scroll function to the improved structure

Fixes #5670

2023-05-31 11:45 UTC, solth approved these changes
Thanks for this fix! Looks correct and seems to work. :+1:

2023-05-31 13:22 UTC, andre-hohmann requested changes
@markusweigelt : 

- It works perfectly, if you are navigating in the "scroll-bar". 
- If you select an object in the structure tree, it works well until object number 100 (roughly). Then, the selected object is out of focus. It seems, as if with every object, the focused object moves down. You should test this with a process of at least 200 objects. Could you check this again?

2023-06-01 09:28 UTC, oliver-stoehr requested changes

2023-06-01 09:28 UTC, oliver-stoehr commented on Kitodo/src/main/webapp/WEB-INF/resources/js/scroll.js
> +    let thumbnailHeight = thumbnail.closest(".thumbnail-parent").height();
```suggestion
    let thumbnailHeight = thumbnail.closest(".thumbnail-parent").outerHeight(true);
```
You could use here `outerHeight` to consider the elements margin and change the following rule in kitodo.css:3167.
```
#imagePreviewForm\:thumbnailWrapper .thumbnail-parent {
    display: block;
    margin-bottom: var(--group-margin);
    margin-left: auto;
    margin-right: auto;
}
```
The `scrolltoPreviewThumbnail` method did not take the spacing between the elements into account when computing the scrollTop value. These changes should do the trick.

2023-06-01 15:52 UTC, markusweigelt commented
Added @oliver-stoehr suggestions, tested the change with more than 200 images and it worked for me.

2023-06-02 12:52 UTC, andre-hohmann approved these changes
@markusweigelt : Thanks a lot! 
From the users' perspective, it works fine now.

2023-06-02 12:54 UTC, oliver-stoehr approved these changes

2023-06-02 16:18 UTC, merged