Improve correction icon
kitodo/kitodo-production pull request #5679
Opened 2023-06-01 15:12 UTC by oliver-stoehr

Replace the correction "C"/"K" with a more universal icon independent of the user language. The new icon matches the style of the other icons used in Kitodo and has the same size as the other icons, thus not breaking the list layout.
The character is replaced by an exclamation icon in a circle:
![Bildschirmfoto 2023-06-01 um 17 06 52](https://github.com/kitodo/kitodo-production/assets/32509444/2582f357-c591-4592-80ad-d263853eb66b)
The color scheme (red/gray) for active/resolved correction comments is kept.

2023-06-05 13:29 UTC, markusweigelt requested changes
Thx for implementation.

In my case it does not work in list views. In the comment column only the speech bubble is visible even if a correction task is active. In task list i do not have such a column to show comment or error icon. How did you set this up these columns?

![image](https://github.com/kitodo/kitodo-production/assets/3832618/d1b5323d-e019-438c-bff4-b9afb592e4dd)

2023-06-06 07:36 UTC, oliver-stoehr commented
@markusweigelt There is no comment column in the tasks widget, but only in the processes widget, the designated processes page and the designated tasks page.

I recently discovered that the comments might not be updated in index properly (see https://github.com/kitodo/kitodo-production/issues/5676). Is the displayed icon also wrong when you rebuild your index?

2023-10-03 15:07 UTC, markusweigelt commented
Unfortunately, the main icon within the process list widget does not change. When hovering over the comment icon, the list of recent comments opens, and that's where you can finally see the correction message.

![image](https://github.com/kitodo/kitodo-production/assets/3832618/e113a914-0705-41bd-a125-71718047aec4)

I couldn't find any additional locations other than the dashboard (as seen in the screenshot). Could you please provide me with more information about where to find the corresponding tasks and process page? We can also clarify this briefly via webcall.

2023-10-06 09:32 UTC, oliver-stoehr commented
@markusweigelt I took another look at the processes widget and fixed the icon in the processes widget.
You can enable the comments column on the processes page and the tasks pages by enabling it via the "configure columns" menu next to the "extended search" button.

2023-10-11 14:56 UTC, markusweigelt commented
@oliver-stoehr Thank you, now it's working for me. The columns in the task and process overviews also display the icon.

2023-10-11 14:57 UTC, markusweigelt approved these changes

2023-10-13 07:36 UTC, merged