Remove unused part of the image management interface
kitodo/kitodo-production pull request #5683
Opened 2023-06-02 07:47 UTC by matthias-ronge

Part of #5580

2024-01-10 10:11 UTC, matthias-ronge commented
@solth Is there a reason why this hasn't been merged yet?

2024-01-10 10:50 UTC, solth commented
@matthias-ronge sorry for not merging this pull request, yet. I just wanted review it and make sure we do not need this code anymore. I will try to review it this week.

2024-01-11 12:39 UTC, solth requested changes
As far as I can see the changes look correct. However, the name of the SQL file needs to be updated to reflect the state of migration files in the current master branch.

Also, please rebase your branch against the current master.

2024-02-26 11:19 UTC, solth approved these changes

2024-02-26 11:25 UTC, merged