Enable edit and delete info-comments
kitodo/kitodo-production pull request #5703
Opened 2023-07-04 13:21 UTC by pontus-osterdahl

This pull request adds the functionality to edit and delete info-comments. Fixes #5702 

* Add editCommentDialog.xhtml

* Enable removal of Comment in CommentService and CommentsForm

* Add integration test for CommentService

* Changed properties of comments association in Process bean

* Add messages for editing and deleting comments

* Update kitodo.css

2023-07-11 07:43 UTC, henning-gerhardt reviewed
fast code only review

2023-07-11 07:43 UTC, henning-gerhardt commented on Kitodo/src/main/java/org/kitodo/production/forms/CommentForm.java
> +            e.printStackTrace();
Use a right logging statement or use the helper method to get the error displayed to the user.

2023-07-11 07:43 UTC, henning-gerhardt commented on Kitodo/src/main/java/org/kitodo/production/services/data/CommentService.java
> +        comment.setCurrentTask(null);
Is this really necessary if the comment will get deleted?

2023-07-12 11:13 UTC, pontus-osterdahl commented
Added changes suggested in comments to https://github.com/kitodo/kitodo-production/issues/5702 (only author is allowed to edit/delete comment and only most recent comment should be edited).

2023-07-17 10:35 UTC, henning-gerhardt reviewed
Changes looks good (except returning `null` but maybe needed in the CommentForm class usage in the UI) but I did not test them nor I'm familiar with the JSF and CSS code, so somebody else should have a more closer look into this and maybe did even test it.

2023-08-18 13:21 UTC, oliver-stoehr requested changes
When I edit a comment in the metadata editor, save the comment and then do one of the following actions:
- Delete the comment
- Click "Exit"
- Click "Save"
- Click "Save & exit"

I run into the following exception:
`javax.el.PropertyNotFoundException: Target Unreachable, [editedComment] returned null`
<details>
<summary>Stacktrace</summary>

```
javax.el.PropertyNotFoundException: Target Unreachable, [editedComment] returned null
	at org.apache.el.parser.AstValue.getTarget(AstValue.java:123)
	at org.apache.el.parser.AstValue.getType(AstValue.java:57)
	at org.apache.el.ValueExpressionImpl.getType(ValueExpressionImpl.java:173)
	at org.jboss.weld.el.WeldValueExpression.getType(WeldValueExpression.java:93)
	at org.jboss.weld.el.WeldValueExpression.getType(WeldValueExpression.java:93)
	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getType(ContextAwareTagValueExpression.java:76)
	at org.primefaces.util.ComponentUtils.getConverter(ComponentUtils.java:160)
	at org.primefaces.renderkit.InputRenderer.getConvertedValue(InputRenderer.java:45)
	at javax.faces.component.UIInput.getConvertedValue(UIInput.java:789)
	at javax.faces.component.UIInput.validate(UIInput.java:708)
	at javax.faces.component.UIInput.processValidators(UIInput.java:293)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:779)
	at org.apache.myfaces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:213)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1019)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
	at javax.faces.component.UIForm.visitTree(UIForm.java:357)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1047)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1047)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1047)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1047)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartialExecute(PartialViewContextImpl.java:435)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:416)
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65)
	at javax.faces.context.PartialViewContextWrapper.processPartial(PartialViewContextWrapper.java:97)
	at org.omnifaces.context.OmniPartialViewContext.processPartial(OmniPartialViewContext.java:122)
	at javax.faces.component.UIViewRoot$ProcessValidatorPhaseProcessor.process(UIViewRoot.java:1880)
	at javax.faces.component.UIViewRoot._process(UIViewRoot.java:1738)
	at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:982)
	at org.apache.myfaces.lifecycle.ProcessValidationsExecutor.execute(ProcessValidationsExecutor.java:38)
	at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:195)
	at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:142)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:204)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.kitodo.production.servletfilter.EncodingFilter.doFilter(EncodingFilter.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.omnifaces.filter.GzipResponseFilter.doFilter(GzipResponseFilter.java:183)
	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:337)
	at org.kitodo.production.security.SecurityObjectAccessFilter.doFilter(SecurityObjectAccessFilter.java:89)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:109)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:147)
	at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:125)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:223)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.springframework.security.web.FilterChai [...]

2023-09-03 09:34 UTC, solth commented
@pontus-osterdahl could you take a look at the problem reported by @oliver-stoehr ?

2023-09-04 05:45 UTC, pontus-osterdahl commented
@oliver-stoehr Thank you for your review and comment!
Unfortunately, I am not able to reproduce the exception.

I first edited and saved an existing comment in the metadata editor and then performed the mentioned actions, but no exception occurs. 

Have I misunderstood your description of the problem?

2023-09-20 08:16 UTC, oliver-stoehr commented
I think you got it right, but I recorded a video just to be clear:
![error](https://github.com/kitodo/kitodo-production/assets/32509444/cc1aa17d-8b72-436d-8288-6ea0830e0a31)

It seems like the `editCommentDialog.xhtml` is rendered after an action like pressing "Save" updated the page. I think the rendering fails because `editedComment` is already set to `null` at that point.
Adding `rendered="#{CommentForm.getEditedComment() ne null}"` to the `editCommentForm` seems to fix the issue!

2023-09-21 07:33 UTC, oliver-stoehr approved these changes

2023-09-21 10:52 UTC, solth commented
@pontus-osterdahl would you mind rebasing your branch against the current master since there have been some fixes for the tests and builds since you first opened this pull request?

2023-09-21 11:37 UTC, pontus-osterdahl commented
@solth done.

2023-09-21 12:19 UTC, solth commented
@pontus-osterdahl thank you for the update. I think something went wrong with the Github logic, though, since your pull request now lists 113 changed files with 2052 added and 474 deleted lines in those files:

<img width="1266" alt="Bildschirmfoto 2023-09-21 um 14 07 57" src="https://github.com/kitodo/kitodo-production/assets/19183925/c2d75fd8-a64a-4e92-b4d6-fe82b54bbc4e">

Your pull request now seems to (wrongly) list all files changed in the master since you first opened your pull request as changed of your pull request and differences between your branch and the master.

The commit message of the merge commit also looks a little suspicious:

<img width="773" alt="Bildschirmfoto 2023-09-21 um 14 14 52" src="https://github.com/kitodo/kitodo-production/assets/19183925/a203a124-1422-4f6a-b61e-7e9720ee7dbd">

Shouldn't this read "Merge branch 'master' of https://github.com/kitodo/kitodo-production into Enable-editing-and-delete-info-comments"? 

Clicking on your branch in your fork however correctly states the number of changed files and lines:

<img width="486" alt="Bildschirmfoto 2023-09-21 um 14 09 38" src="https://github.com/kitodo/kitodo-production/assets/19183925/744873a2-5df2-4d8f-88ae-031247c56cea">

so I guess the branch itself is in the correct state, just the pull request is somehow broken.

I am not sure what went wrong here but I have a bad feeling about merging this pull request in this form. Could you open a new pull request from the branch - without any additional changes - to see if it will state the number of changes correctly?

2023-09-21 18:22 UTC, pontus-osterdahl commented
@solth Thanks for your comment and please excuse the inconvenience! I opened a new pull request #5785.

2023-10-13 06:29 UTC, merged