Enable editing and delete info comments patch
kitodo/kitodo-production pull request #5785
Opened 2023-09-21 18:18 UTC by pontus-osterdahl

This pull request adds the functionality to edit and delete info-comments. Fixes https://github.com/kitodo/kitodo-production/issues/5702 . Fixes issues with pull request #5703 

* Add editCommentDialog.xhtml
* Enable removal of Comment in CommentService and CommentsForm
* Add integration test for CommentService

 * Changed properties of comments association in Process bean

* Add messages for editing and deleting comments
* Update kitodo.css

2023-10-04 07:19 UTC, solth commented
@pontus-osterdahl thanks for opening a new pull request! This looks much better now! Unfortunately, merging the older PR #5657 now created a conflict with your code. Could you please resolve the conflict? Then this PR is next to merge candidate.

2023-10-06 12:24 UTC, solth reviewed
@pontus-osterdahl Thank you for resolving the conflict!

I just tested your branch and it worked as intended. I just noticed some small issue: when deleting the last comment of a process, the "comments" column in the process list still shows the icon to mark the existence of comments, but the mouse over popup is empty:

<img width="227" alt="Bildschirmfoto 2023-10-06 um 14 01 59" src="https://github.com/kitodo/kitodo-production/assets/19183925/00f6550c-2168-4581-819d-969e722f02e3">

It seems this happens because the `ProcessDTO.hasComments` property is not re-evaluated when deleting existing comments.

2023-10-09 11:34 UTC, pontus-osterdahl commented
Thanks @solth for noticing this issue. The process containing the edited/deleted comment was not indexed. I have pushed a patch which should solve the issue. Or should we await the Hibernate Search integration?

2023-10-10 10:51 UTC, solth reviewed
Seems to work very well now. I have just one more minor change suggestion to slightly improve the code at one place (see above).

2023-10-10 14:24 UTC, pontus-osterdahl commented on Kitodo/src/main/java/org/kitodo/production/forms/CommentForm.java
>              ServiceManager.getCommentService().removeComment(comment);
Thanks again! I agree and would tend to make it non static.

2023-10-11 18:06 UTC, solth requested changes
Thanks again. Just found a few unused import that should be removed before merging.

2023-10-11 18:06 UTC, solth commented on Kitodo/src/main/java/org/kitodo/production/services/data/CommentService.java
> +import org.kitodo.data.database.beans.User;
```suggestion
```
Unused import

2023-10-11 18:06 UTC, solth commented on Kitodo/src/main/java/org/kitodo/production/services/data/CommentService.java
> +import java.io.IOException;
```suggestion
```
Unused import

2023-10-11 18:06 UTC, solth commented on Kitodo/src/main/java/org/kitodo/production/services/data/CommentService.java
> +import org.kitodo.data.exceptions.DataException;
```suggestion
```
Unused import

2023-10-11 18:06 UTC, solth commented on Kitodo/src/main/webapp/WEB-INF/templates/includes/comments/editCommentDialog.xhtml
> +        xmlns:f="http://xmlns.jcp.org/jsf/core"
```suggestion
```
Unused xml namespace

2023-10-11 18:06 UTC, solth commented on Kitodo/src/test/java/org/kitodo/production/services/data/CommentServiceIT.java
> +import org.junit.Rule;
```suggestion
```
Unused import

2023-10-11 18:06 UTC, solth commented on Kitodo/src/test/java/org/kitodo/production/services/data/CommentServiceIT.java
> +import org.junit.rules.ExpectedException;
```suggestion
```
Unused import

2023-10-11 18:06 UTC, solth commented on Kitodo/src/test/java/org/kitodo/production/services/data/CommentServiceIT.java
> +import org.kitodo.data.database.beans.Task;
```suggestion
```
Unused import

2023-10-11 21:56 UTC, solth approved these changes

2023-10-13 06:29 UTC, merged