Adjust metada replacement
kitodo/kitodo-production pull request #5800
Opened 2023-10-05 14:54 UTC by henning-gerhardt

fixes #5799

2023-10-23 09:22 UTC, matthias-ronge commented
This fix is a functional change. Previously, with $meta.x variables only the first child was checked, and if this is empty, the variable is resolved on the top structure.

With this change, the first grandchild is now also taken into account, which would result in a different output value in other constellations:

```
📄 topstruct
  ├─ 📝 md: Foo
  └─ 📄 firstchild
      └─ 📄 firstgrandchild
          └─ 📝 md: Bar
```
Before: $(meta.md) → “Foo” (firstchild has no ‘md’, so resolve from topstruct)  
After: $(meta.md) → “Bar” (firstchild has no ‘md’, found on firstgrandchild, value from topstruct ignored)

Maybe fix like this:
```java
       if (!allChildren.isEmpty()) {
           allFirstchildValue = MetadataEditor.getMetadataValue(allChildren.get(0), variableFinder.group(5));
/*»*/      if (Objects.isNull(allFirstchildValue)) {                                                     
/*»*/          allFirstchildValue = determineReplacementForTopstruct(variableFinder, dollarSignIfToKeep);
/*»*/      }
           if (Objects.isNull(allFirstchildValue)) {
               List<LogicalDivision> firstChildChildren = allChildren.get(0).getChildren();
               if (!firstChildChildren.isEmpty()) {
                   allFirstchildValue = MetadataEditor.getMetadataValue(firstChildChildren.get(0), variableFinder.group(5));
               }
           }
       }
```

This should maintain the original behaviour, and fix your problem as well.

2023-10-23 09:23 UTC, matthias-ronge requested changes
See comment above

2023-10-23 13:43 UTC, henning-gerhardt commented
My intention was to look first into the first child and then in the first grandchild and if both locations are not returning an result look into the top element. 

But your code change suggestion is not working without an other needed change: `determineReplacementForTopstruct` method is returning an empty string if in the top element not result is found (hidden by the `dollarSignIfToKeep` variable which is used as return value in not found case and the `dollarSignIfToKeep` variable is an empty string in many cases) so the following check condition must be extended to check for an empty string to get the right meta data.

2023-11-29 07:20 UTC, matthias-ronge requested changes
Just one more little thing.

2023-11-29 07:20 UTC, matthias-ronge commented on Kitodo/src/main/java/org/kitodo/production/helper/VariableReplacer.java
> +            if (Objects.isNull(allFirstchildValue) || StringUtils.isEmpty(allFirstchildValue)) {
[`StringUtils.isEmpty()`](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#isEmpty-java.lang.CharSequence-) implies a `null` check, so you can remove the `Objects.isNull()` check

2023-12-04 12:32 UTC, matthias-ronge approved these changes

2023-12-04 12:45 UTC, merged