Add missing clone method to Course class
kitodo/kitodo-production pull request #5977
Opened 2024-03-04 12:35 UTC by henning-gerhardt

According to CodeQL the Course class is missing a `clone` method to extend the `ArrayList` base class complete.

2024-05-03 11:02 UTC, solth requested changes
Please rebase against current master

2024-05-13 11:12 UTC, henning-gerhardt commented on Kitodo/src/test/resources/newspaper-course.xml
> +<?xml version="1.0" encoding="UTF-8"?>
License header added.

2024-05-13 11:13 UTC, henning-gerhardt commented on Kitodo/src/test/java/org/kitodo/production/model/bibliography/course/CourseTest.java
> +class CourseTest {
Made class and method public.

2024-05-13 11:13 UTC, henning-gerhardt commented
PR is rebased.

2024-05-14 11:16 UTC, solth approved these changes

2024-05-14 11:19 UTC, merged