Metadata editor tests
kitodo/kitodo-production pull request #6028
Opened 2024-04-09 14:39 UTC by solth

This pull request adds tests for the metadata editor.

Part of https://github.com/orgs/kitodo/projects/8

2024-05-13 13:02 UTC, solth commented
> Just a question: is it possible to change the Junit4 to Junit5 tests in the new test classes? Changing it could be fast done but sometimes even tricky and maybe with a lot of time.

Good point. I will try to adjust the tests accordingly and re-open the PR for review afterwards.

2024-05-14 08:28 UTC, solth commented
@henning-gerhardt I updated the tests to JUnit5.

2024-05-14 08:35 UTC, henning-gerhardt requested changes
The order of import statements should be correct and maybe import the different Assertions as static import as this should improve the reading quality of code.

2024-05-14 08:35 UTC, henning-gerhardt commented on Kitodo/src/test/java/org/kitodo/production/forms/dataeditor/DataEditorFormTest.java
> +import java.util.Objects;
Wrong order of import statements.

2024-05-14 08:35 UTC, henning-gerhardt commented on Kitodo/src/test/java/org/kitodo/production/services/data/DataEditorServiceIT.java
> +import javax.faces.model.SelectItem;
Wrong order of import statements.

2024-05-14 08:35 UTC, henning-gerhardt commented on Kitodo/src/test/java/org/kitodo/production/forms/dataeditor/DataEditorFormTest.java
> +        Assertions.assertTrue(dataEditorForm.consecutivePagesSelected(),
Maybe import the Assertions.* as static imports?

2024-05-14 11:14 UTC, merged