Improve handle sessions
kitodo/kitodo-production pull request #6047
Opened 2024-04-22 09:34 UTC by matthias-ronge

- move logout handling from version management to session management (clean-up)
- log warnings if logout fails

2024-04-22 13:47 UTC, matthias-ronge commented
Doesn’t work

2024-05-08 07:47 UTC, solth commented on Kitodo/src/main/java/org/kitodo/production/security/CustomLogoutSuccessHandler.java
> +                    logger.warn(MessageFormat.format("Cannot expire session: {0} !instanceof UserDetails",
I am not a friend of this code like syntax in natual lanaguage logs. Can we change this to "{0}  is not an instance of 'UserDetails'" or something similar? (the `!` is easy to overlook in a log message, in my opinion)

2024-05-08 07:47 UTC, solth commented on Kitodo/src/main/java/org/kitodo/production/services/security/SessionService.java
> +                logger.warn(MessageFormat.format("Cannot expire session: {0} !instanceof SecurityUserDetails",
See above.

2024-05-08 07:47 UTC, solth commented on Kitodo/src/main/java/org/kitodo/production/services/security/SessionService.java
> +            logger.warn(MessageFormat.format("Cannot expire session: {0} !instanceof SecurityContextImpl",
See above.

2024-08-13 20:56 UTC, solth requested changes
@matthias-ronge thanks for updating the log messages. Please rebase your branch against the master and resolve the current merge conflict.

2024-08-23 08:29 UTC, solth approved these changes
Thanks for resolving the merge conflict.

2024-08-23 10:10 UTC, merged